# Generated by Django 6.0.1 on 2026-03-24 03:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('L', 'Low'), ('M', 'Medium'), ('H', 'High')], default='M', max_length=1),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['user'], name='todoapp_tas_user_id_e2c3f4_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['complete'], name='todoapp_tas_complet_3bfdfd_idx'),
        ),
    ]
